services:
  backend:
    build: backend/
    container_name: backend
    depends_on:
      - postgres
    networks:
      - postgres-network
    environment:
      - DATABASE_HOST=postgres
    env_file:
      - backend/.env
    restart: unless-stopped

  frontend:
    build: frontend/
    container_name: frontend
    networks:
      - postgres-network
    volumes:
      - frontend-dist:/usr/src/app/dist
    env_file:
      - frontend/.env

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=prac
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS=10
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    ports:
      - 8080:80
    networks:
      - postgres-network
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - frontend
    ports:
      - 80:80
      - 443:443
    networks:
      - postgres-network
    restart: always
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - frontend-dist:/var/www/frontend:ro

networks:
  postgres-network:

volumes:
  postgres-data:
  pgadmin-data:
  frontend-dist:
